<?php

use \Nwdthemes\Revslider\Model\Revslider\RevSliderAdmin;

/**
 * @author    ThemePunch <info@themepunch.com>
 * @link      http://www.themepunch.com/
 * @copyright 2015 ThemePunch
 */

?>
<input type="hidden" id="sliderid" value="<?php echo $sliderID; ?>"></input>

<?php
$is_edit = true;
echo $this->getChildBlock('slider-main-options')
    ->assign([
        'block' => $block,
        'framework' => $framework,
        'query' => $query,
        'curl' => $curl,
        'filesystemHelper' => $filesystemHelper,
        'images' => $images,
        'resource' => $resource,
        'googleFonts' => $googleFonts,
        'postTypesWithCats' => $postTypesWithCats,
        'sliderID' => $sliderID,
        'arrFieldsParams' => $arrFieldsParams,
        'uslider' => $uslider,
        'slider' => $slider,
        'linksEditSlides' => $linksEditSlides,
        'is_edit' => $is_edit
    ])
    ->toHtml();
?>

<script type="text/javascript">
	var g_jsonTaxWithCats = <?php echo $jsonTaxWithCats?>;

	require(['jquery', 'revAdmin'], function(jQuery, RevSliderAdmin) {
        jQuery(document).ready(function(){
        	RevSliderAdmin.initEditSliderView();
        });
	});
</script>