<div class="slider-revolution-update-list">


<h3 class="version-number">Version 5.2.6.3 StarPath (28th October 2016)</h3>
<div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
<ul>
    <li>Add to cart action added to layer actions for product based sliders</li>
</ul>
<div class="bugfix"><strong style="font-weight:700">CHANGES</strong></div>
<ul>
    <li>Disabled autoload when checking for class existance</li>
    <li>Removed unused WMPL related code</li>
</ul>
<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
<ul>
    <li>Fixed error on saving custom slider preset</li>
</ul>
    


<h3 class="version-number">Version 5.2.6.2 StarPath (15th October 2016)</h3>
<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
<ul>
    <li>Forced https protocol on sliders thumbnails urls</li>
    <li>Fixed ajax error bug when saving slide after duplicating layer</li>
    <li>Removed deprecated characters from name attribute in backend layout</li>
    <li>Fix for missing title attribute in ACL resource</li>
    <li>Fix for undefined function error warning when importing template online</li>
</ul>



<h3 class="version-number">Version 5.2.6.1 StarPath (1st September 2016)</h3>
<div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
<ul>
    <li>Positioned manual animation timing dialog to layer it was called for</li>
</ul>
<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
<ul>
    <li>Setting default font family if not specified on captions saving</li>
    <li>Updated translation functions calls</li>
    <li>Minified addons scripts</li>
    <li>Removed depricated use of old Magento helpers</li>
</ul>
<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
<ul>
    <li>Fixed bug with importing template sliders for databases with custom table prefix</li>
    <li>Fixed bug with edit layers timeline split text time incorrectly added to each layer</li>
    <li>Fix for add slider enter title dialog displaying under templates shop dialog</li>
    <li>Fix for showing all hidden dialogs after image inserting</li>
    <li>Fix for delete confirmation popover displaying under select image slide out dialog</li>
    <li>Fix for guide lines zindex issue with save styles dropdown</li>
    <li>Fix for color picker edit field zindex</li>
    <li>Fix for preview captions after inserting new caption style</li>
    <li>Fix for navigation save function</li>
    <li>Fix for saving css captions</li>
    <li>Fix for dialog zIndex problems</li>
    <li>Fix for javascript error on slide editor</li>
    <li>Fix for color picker edit field</li>
    <li>Fix for not showing inline css template and layer dialogs</li>
    <li>Fix for media gallery dialog z-index issue</li>
    <li>Fixed typo in video settings autoplay option</li>
    <li>Fix for audio mp3 layer in slide editor. Fix for whiteboard addon</li>
    <li>Fixed error with backup addons</li>
    <li>Fix for left arrow override</li>
    <li>Fix for svg import from template</li>
    <li>Fix for product based slider slide links</li>
    <li>Fix for product based view link, prices and preview</li>
</ul>



<h3 class="version-number">Version 5.2.6 StarPath (28th July 2016)</h3>
<div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
<ul>
    <li>Slider Revolution Magento 2 Extension Version Created!</li>
</ul>